# atac_bigwigs_merged.sub

# set CHTC universe ----------------------------------------------------------------------
universe = vanilla

# set job requirements -------------------------------------------------------------------
Requirements = (Target.HasCHTCStaging == true)

# set output files -----------------------------------------------------------------------
log = atac_bigwigs_merged_$(Cluster).log
error = atac_bigwigs_merged_$(Cluster).err
output = atac_bigwigs_merged_$(Cluster).out


# set executable and arguments ------------------------------------------------------------
executable = ./atac_bigwigs_merged.sh
arguments =  "'$(in_dir)' '$(out_dir)' '$(ref_dir)' '$(group_name)' '$(replicates)'"
transfer_input_files = /home/tjgibson2/programs/samtools

# transfer output files ------------------------------------------------------------------
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# request resources ------------------------------------------------------------------------
request_cpus = 1
request_memory = 16GB
request_disk = 60GB


# queue job ------------------------------------------------------------------------------
queue
