# download_SRA.sub

# set CHTC universe ----------------------------------------------------------------------
universe = vanilla

# set job requirements -------------------------------------------------------------------
Requirements = (Target.HasCHTCStaging == true)

# set output files -----------------------------------------------------------------------
log = $(bn)_download_SRA_$(Cluster).log
error = $(bn)_download_SRA_$(Cluster).err
output = $(bn)_download_SRA_$(Cluster).out


# set executable and arguments ------------------------------------------------------------
executable = ./download_SRA.sh
arguments =  "'$(sra_id)' '$(out_dir)'"
transfer_input_files = /home/tjgibson2/programs/sratoolkit.2.10.5-centos_linux64.tar.gz
# transfer output files ------------------------------------------------------------------
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# request resources ------------------------------------------------------------------------
request_cpus = 1
request_memory = 8GB
request_disk = 40GB


# queue job ------------------------------------------------------------------------------
queue
