# feature_counts.sub

# set CHTC universe ----------------------------------------------------------------------
universe = vanilla

# set job requirements -------------------------------------------------------------------
Requirements = (Target.HasCHTCStaging == true)

# set output files -----------------------------------------------------------------------
log = $(bn)_feature_counts_$(Cluster).log
error = $(bn)_feature_counts_$(Cluster).err
output = $(bn)_feature_counts_$(Cluster).out


# set executable and arguments ------------------------------------------------------------
executable = ./feature_counts.sh
arguments =  "'$(bam)' '$(SAF_file)' '$(in_dir)'"
transfer_input_files = /home/tjgibson2/programs/subread-1.6.4-Linux-x86_64.tar.gz

# transfer output files ------------------------------------------------------------------
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# request resources ------------------------------------------------------------------------
request_cpus = 1
request_memory = 16GB
request_disk = 20GB


# queue job ------------------------------------------------------------------------------
queue
