# filter_reads.sub

# set CHTC universe ----------------------------------------------------------------------
universe = vanilla

# set job requirements -------------------------------------------------------------------
Requirements = (Target.HasCHTCStaging == true && Target.HasJava == true)

# set output files -----------------------------------------------------------------------
log = $(Cluster)_$(Process).log
error = $(Cluster)_$(Process).err
output = $(Cluster)_$(Process).out


# set executable and arguments ------------------------------------------------------------
executable = ./filter_reads.sh
arguments =  "'$(bam)' '$(in_dir)' '$(out_dir)' '$(bn)'"
transfer_input_files = /home/tjgibson2/programs/samtools, /home/tjgibson2/programs/picard.jar, /home/tjgibson2/reference_data/good_chroms.bed

# transfer output files ------------------------------------------------------------------
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# request resources ------------------------------------------------------------------------
request_cpus = 1
request_memory = 16GB
request_disk = 20GB


# queue job ------------------------------------------------------------------------------
queue
