# FILENAME

# set CHTC universe ----------------------------------------------------------------------
universe = vanilla

# set job requirements -------------------------------------------------------------------
Requirements = (Target.HasCHTCStaging == true)

# set output files -----------------------------------------------------------------------
log = $(Cluster)_$(Process).log
error = $(Cluster)_$(Process).err
output = $(Cluster)_$(Process).out


# set executable and arguments ------------------------------------------------------------
executable = ./scripts/executables/process_ATAC.sh
arguments = $(file)
transfer_input_files = ./programs/hisat2-2.1.0.tar.gz

# transfer output files ------------------------------------------------------------------
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# request resources ------------------------------------------------------------------------
request_cpus = 1
request_memory = 8GB
request_disk = 15GB


# queue job ------------------------------------------------------------------------------
queue
