# trim_PE_NGmerge.sh

# set CHTC universe ----------------------------------------------------------------------
universe = vanilla

# set job requirements -------------------------------------------------------------------
Requirements = (Target.HasCHTCStaging == true)

# set output files -----------------------------------------------------------------------
log = $(bn)_trim_PE_NGmerge_$(Cluster).log
error = $(bn)_trim_PE_NGmerge_$(Cluster).err
output = $(bn)_trim_PE_NGmerge_$(Cluster).out


# set executable and arguments ------------------------------------------------------------
executable = ./trim_PE_NGmerge.sh
arguments =  "'$(r1)' '$(r2)' '$(in_dir)' '$(out_dir)' '$(bn)'"
transfer_input_files = /home/tjgibson2/programs/NGmerge.tar.gz

# transfer output files ------------------------------------------------------------------
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# request resources ------------------------------------------------------------------------
request_cpus = 1
request_memory = 8GB
request_disk = 40GB


# queue job ------------------------------------------------------------------------------
queue
